### ISSUE TITLE
重复引用的对象应使用变量保存起来，使得代码更短，性能更高

### ISSUE THREAD

**Issue by mwc** [SapIdeaSoft/UI-QualityAssurance#5]
js/acceptProgressM.js 文件中：

![image](https://cloud.githubusercontent.com/assets/119984/16864294/f8588816-4a8d-11e6-979b-1c16bbc43392.png)

应改为：

![image](https://cloud.githubusercontent.com/assets/119984/16864310/23b366b6-4a8e-11e6-89d3-f6e9e8ec5684.png)

**Comment by SweetJamie** [comment]
created内容已提到公用样式里面
